-- 1. BASIC GROUP BY: Average salary by gender
	-- Added ROUND decimal places and an alias (AS) for cleaner analytics reporting.
		SELECT gender, ROUND(AVG(salary), 2) AS avg_salary 
		FROM users 
		GROUP BY gender;

-- 2. GROUP BY WITH COUNT: Counting occurrences
	-- Capitalized keywords for consistency. 
		SELECT referred_by_id, COUNT(*) AS total_referred
		FROM users
		WHERE referred_by_id IS NOT NULL
		GROUP BY referred_by_id;

-- 3. THE HAVING CLAUSE: Filtering groups
	-- Rule: WHERE filters rows BEFORE grouping. HAVING filters AFTER grouping.
		SELECT gender, AVG(salary) AS avg_salary
		FROM users
		GROUP BY gender
		HAVING AVG(salary) > 65000;

-- 4. COMBINING WHERE AND HAVING: Groups with more than 1 referral
	-- Demonstrates the correct order of clauses in a single query.
		SELECT referred_by_id, COUNT(*) AS total_referred
		FROM users
		WHERE referred_by_id IS NOT NULL
		GROUP BY referred_by_id
		HAVING COUNT(*) > 1;

-- 5. WITH ROLLUP: Subtotals and Grand Totals
	-- ROLLUP adds an extra row representing the grand total. 
	-- Note: The grouped column label will show as NULL for the grand total row.
		SELECT gender, COUNT(*) AS total_users
		FROM users
		GROUP BY gender WITH ROLLUP;

/* =========================================================================
   ADDED FOR ADVANCED ANALYTICS
   ========================================================================= */
-- 6. HANDLING ROLLUP NULLS (Pro-Tip)
	-- Using COALESCE to replace the NULL generated by ROLLUP with 'Grand Total'.
		SELECT COALESCE(department_id, 'Grand Total') AS department_group, COUNT(*) AS total_users
		FROM users
		GROUP BY department_id WITH ROLLUP;

-- 7. MULTIPLE COLUMN GROUP BY
	-- Groups data into more granular buckets (e.g., gender within each department).
		SELECT department_id, gender, COUNT(*) AS total_users, AVG(salary) AS avg_salary
		FROM users
		GROUP BY department_id, gender
		ORDER BY department_id, gender;

-- 8. GROUP_CONCAT: Aggregating text
	-- Highly useful in MySQL analytics to combine row values into a comma-separated list.
		SELECT department_id, GROUP_CONCAT(name) AS employee_names
		FROM users
		GROUP BY department_id;

/* =========================================================================
   SUMMARY & ORDER OF EXECUTION
   =========================================================================
   When writing SQL queries, the logical order of execution is crucial:
   
   1. FROM / JOIN:  Identifies the source tables.
   2. WHERE:        Filters individual rows BEFORE any grouping happens.
   3. GROUP BY:     Aggregates the remaining rows into logical groups.
   4. HAVING:       Filters the grouped records based on aggregate conditions.
   5. SELECT:       Selects the columns and calculates the final expressions.
   6. ORDER BY:     Sorts the final result set.
   7. LIMIT:        Restricts the number of returned rows.

   Key Takeaways for Data Analytics:
   - Always use an alias (AS) for aggregate functions (AVG, SUM, COUNT, MIN, MAX) 
     so exported reports have clean column headers.
   - You cannot use aliases defined in the SELECT clause inside the WHERE clause, 
     but MySQL (unlike some SQL flavors) does allow them in the HAVING clause.
   - Standard SQL practice dictates that any non-aggregated column in your SELECT 
     statement MUST be included in your GROUP BY statement.
   ========================================================================= */